# Project information
site_name: Heroic Labs Documentation
site_description: Documentation for the Nakama realtime and social server for games and apps.
site_author: Heroic Labs Team & Contributors
site_url: https://heroiclabs.com/
edit_uri: https://github.com/heroiclabs/nakama-docs/edit/master/docs/

# Deployment
remote_name: origin
remote_branch: gh-pages

# Repository
repo_name: heroiclabs/nakama
repo_url: https://github.com/heroiclabs/nakama

# Copyright
copyright: Copyright &copy; 2021 Heroic Labs

# Documentation and theme
theme:
  name: material
  language: en
  logo: images/logo-white.svg
  favicon: images/favicon.ico
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.indexes
    - navigation.sections
    - navigation.top
    # Top level navigation turned into tabs
    # Use to implement Nakama Docs Realms
    - navigation.tabs

extra_javascript:
  - javascripts/main.js

extra_css:
  - css/extra.css

# Options
plugins:
  - search:
      lang:
        - en
  - redirects:
      redirect_maps:
          'introduction.md': 'nakama/getting-started/introduction.md'
          'install-docker-quickstart.md': 'nakama/getting-started/docker-quickstart.md'
          'install-binary-windows-quickstart.md' : 'nakama/getting-started/binary-windows-quickstart.md'
          'install-binary-macos-quickstart.md' : 'nakama/getting-started/binary-macos-quickstart.md'
          'install-binary-linux-quickstart.md' : 'nakama/getting-started/binary-linux-quickstart.md'
          'install-server-cli.md': 'nakama/getting-started/server-cli.md'
          'install-configuration.md': 'nakama/getting-started/configuration.md'
          'install-nakama-upgrade.md': 'nakama/getting-started/upgrade.md'
          'console-overview.md': 'nakama/getting-started/console-overview.md'
          'unity-client-guide.md': 'nakama/client-libraries/unity-client-guide.md'
          'javascript-client-guide.md': 'nakama/client-libraries/javascript-client-guide.md'
          'godot-client-guide.md': 'nakama/client-libraries/godot-client-guide.md'
          'defold-client-guide.md': 'nakama/client-libraries/defold-client-guide.md'
          'android-java-client-guide.md': 'nakama/client-libraries/android-java-client-guide.md'
          'cpp-client-guide.md': 'nakama/client-libraries/cpp-client-guide.md'
          'unreal-client-guide.md': 'nakama/client-libraries/unreal-client-guide.md'
          'cocos2d-x-client-guide.md': 'nakama/client-libraries/cocos2d-x-client-guide.md'
          'cocos2d-x-js-client-guide.md': 'nakama/client-libraries/cocos2d-x-js-client-guide.md'
          'authentication.md': 'nakama/concepts/authentication.md'
          'user-accounts.md': 'nakama/concepts/user-accounts.md'
          'tutorial-initialize-new-user.md': 'nakama/tutorials/server/initialize-new-user.md'
          'session.md': 'nakama/concepts/session.md'
          'expert-auth.md': 'nakama/concepts/session-management.md'
          'storage-collections.md': 'nakama/concepts/collections.md'
          'storage-access-controls.md': 'nakama/concepts/access-controls.md'
          'social-friends.md': 'nakama/concepts/friends.md'
          'social-groups-clans.md': 'nakama/concepts/groups-clans.md'
          'social-in-app-notifications.md': 'nakama/concepts/in-app-notifications.md'
          'social-status.md': 'nakama/concepts/status.md'
          'social-realtime-chat.md': 'nakama/concepts/realtime-chat.md'
          'social-realtime-parties.md': 'nakama/concepts/parties.md'
          'gameplay-leaderboards.md': 'nakama/concepts/leaderboards.md'
          'gameplay-tournaments.md': 'nakama/concepts/tournaments.md'
          'gameplay-matchmaker.md': 'nakama/concepts/matches.md'
          'nakama/concepts/matches.md': 'nakama/concepts/matchmaker.md'
          'gameplay-multiplayer-realtime.md': 'nakama/concepts/client-relayed-multiplayer.md'
          'gameplay-multiplayer-server-multiplayer.md': 'nakama/concepts/server-authoritative-multiplayer.md'
          'iap-validation.md': 'nakama/concepts/iap-validation.md'
          'runtime-code-basics.md': 'nakama/server-framework/basics.md'
          'runtime-code-typescript-setup.md': 'nakama/server-framework/typescript-setup.md'
          'runtime-code-go-setup.md': 'nakama/server-framework/go-setup.md'
          'runtime-code-lua-setup.md': 'nakama/server-framework/lua-setup.md'
          'runtime-code-function-reference.md': 'nakama/server-framework/function-reference.md'
          'tutorial-send-push-messages.md': 'nakama/tutorials/server/send-push-messages.md'
          'runtime-code-daily-rewards.md': 'nakama/tutorials/server/daily-rewards.md'
          'tutorial-remote-configuration.md': 'nakama/tutorials/server/remote-configuration.md'
          'tutorial-fishgame-unity.md': 'nakama/tutorials/unity/fishgame.md'
          'tutorial-xoxo-js.md': 'nakama/tutorials/js/xoxo.md'
          'deployment-digital-ocean.md': 'nakama/guides/digital-ocean.md'
          'advanced-events.md': 'nakama/concepts/events.md'
          'advanced-streams.md': 'nakama/server-framework/streams.md'
          'expert-modelling.md': 'nakama/concepts/scalability-modeling.md'
          'expert-tcp-udp.md': 'nakama/concepts/tcp-vs-udp.md'
          'benchmarks.md': 'nakama/getting-started/benchmarks.md'
          'nakama/concepts/server-relayed-multiplayer.md': 'nakama/concepts/server-authoritative-multiplayer.md'

extra:
  social:
    - icon: fontawesome/solid/globe
      link: https://heroiclabs.com
    - icon: fontawesome/brands/github
      link: https://github.com/heroiclabs
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/heroicdev
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/heroic-labs

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      linenums: False
      guess_lang: False
  - toc:
      permalink: True
  - pymdownx.superfences
  - pymdownx.tabbed

# Nav menu
nav:
  - Nakama Server:
    - Getting Started:
      - Introduction: nakama/getting-started/introduction.md
      - Architecture Overview: nakama/getting-started/architecture-overview.md
      - Download and install:
        - Docker compose: nakama/getting-started/docker-quickstart.md
        - Windows binary: nakama/getting-started/binary-windows-quickstart.md
        - macOS binary: nakama/getting-started/binary-macos-quickstart.md
        - Linux binary: nakama/getting-started/binary-linux-quickstart.md
      - Nakama CLI: nakama/getting-started/server-cli.md
      - Nakama Console: nakama/getting-started/console-overview.md
      - Configuration: nakama/getting-started/configuration.md
      - Upgrading Nakama: nakama/getting-started/upgrade.md
      - Benchmarks: nakama/getting-started/benchmarks.md
      - Previous releases: previous-versions.md
    - Concepts:
      - Authentication: nakama/concepts/authentication.md
      - Sessions:
        - Sessions: nakama/concepts/session.md
        - Session management: nakama/concepts/session-management.md
      - Users:
        - User accounts: nakama/concepts/user-accounts.md
        - Initialize new users: nakama/tutorials/server/initialize-new-user.md
      - Storage Engine:
        - Collections: nakama/concepts/collections.md
        - Access controls: nakama/concepts/access-controls.md
        - Modeling for scalability: nakama/concepts/scalability-modeling.md
      - Friends: 
        - Friends: nakama/concepts/friends.md
        - Best Practices: nakama/concepts/friends-best-practices.md
      - Status: nakama/concepts/status.md
      - Groups and Clans: nakama/concepts/groups-clans.md
      - Real-time Parties: nakama/concepts/parties.md
      - Chat: nakama/concepts/realtime-chat.md
      - Leaderboards: nakama/concepts/leaderboards.md
      - Tournaments: nakama/concepts/tournaments.md
      - Notifications: nakama/concepts/in-app-notifications.md
      - Multiplayer Engine:
        - Real-time Matchmaker: nakama/concepts/matches.md
        - Client-relayed multiplayer: nakama/concepts/client-relayed-multiplayer.md
        - Server authoritative multiplayer: nakama/concepts/server-authoritative-multiplayer.md
      - IAP Validation: nakama/concepts/iap-validation.md
      - Events: nakama/concepts/events.md
      - Choosing TCP or UDP: nakama/concepts/tcp-vs-udp.md
    - Server Framework:
      - Basics: nakama/server-framework/basics.md
      - TypeScript Setup: nakama/server-framework/typescript-setup.md
      - Go Setup: nakama/server-framework/go-setup.md
      - Lua Setup: nakama/server-framework/lua-setup.md
      - Streams: nakama/server-framework/streams.md
      - Go Dependency Pinning: nakama/server-framework/go-dependency-pinning.md
      - Recipes:
          - Itch.io Authentication: nakama/server-framework/recipes/itch-authentication.md
          - Updating User Metadata: nakama/server-framework/recipes/updating-user-metadata.md
          - Updating Group Metadata: nakama/server-framework/recipes/updating-group-metadata.md
          - Authoritative In-game Items: nakama/server-framework/recipes/handling-player-equipment-authoritatively.md
          - Authoritative Storage: nakama/server-framework/recipes/writing-to-storage-authoritatively.md
      - Function Reference: nakama/server-framework/function-reference.md
    - Client Libraries:
      - .NET/Unity: nakama/client-libraries/unity-client-guide.md
      - JavaScript: nakama/client-libraries/javascript-client-guide.md
      - Godot: nakama/client-libraries/godot-client-guide.md
      - Defold : nakama/client-libraries/defold-client-guide.md
      - Java/Android: nakama/client-libraries/android-java-client-guide.md
      - C++: nakama/client-libraries/cpp-client-guide.md
      - Unreal: nakama/client-libraries/unreal-client-guide.md
      - Cocos2d-x C++: nakama/client-libraries/cocos2d-x-client-guide.md
      - Cocos2d-x JS: nakama/client-libraries/cocos2d-x-js-client-guide.md
    - Tutorials:
      - Push messages: nakama/tutorials/server/send-push-messages.md
      - Daily Rewards: nakama/tutorials/server/daily-rewards.md
      - Remote configuration: nakama/tutorials/server/remote-configuration.md
      - SendGrid integration: nakama/tutorials/server/sendgrid.md
      - Unity:
        - Fish Game: nakama/tutorials/unity/fishgame.md
        - Pirate Panic:
          - Introduction: nakama/tutorials/unity/pirate-panic/intro.md
          - Authentication: nakama/tutorials/unity/pirate-panic/authentication.md
          - Friends and Chat: nakama/tutorials/unity/pirate-panic/friends.md
          - Clans: nakama/tutorials/unity/pirate-panic/clans.md
          - Storage: nakama/tutorials/unity/pirate-panic/storage.md
          - Matchmaking: nakama/tutorials/unity/pirate-panic/matchmaking.md
          - Realtime Multiplayer: nakama/tutorials/unity/pirate-panic/realtime-multiplayer.md
          - Leaderboards: nakama/tutorials/unity/pirate-panic/leaderboards.md
          - Notifications: nakama/tutorials/unity/pirate-panic/notifications.md
      - JavaScript:
        - Phaser tic-tac-toe: nakama/tutorials/js/xoxo.md
    - Guides:
      - Bucketed Leaderboards: nakama/guides/bucketed-leaderboards/index.md
      - Group & Friend Leaderboards: nakama/guides/group-leaderboards/index.md
      - Tiered Leagues/Seasons: nakama/guides/leagues.md
      - Guarding APIs: nakama/guides/guarding-apis.md
      - Asset Management: nakama/guides/asset-management/index.md
      - Deploy to Digital Ocean: nakama/guides/digital-ocean.md
      - Migrating from GameSparks: nakama/guides/gamesparks-migration.md
  - Heroic Cloud:
    - Introduction: heroic-cloud/introduction.md
    - Organizations: heroic-cloud/organizations.md
    - Projects: heroic-cloud/projects.md
    - Builders: heroic-cloud/builders.md
